<?php

namespace AppBundle\Entity;

/**
 * ChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Child p ORDER BY p.name ASC'
            )
            ->getResult();
    }

    public function learnDQL()
    {
//        $dql = 'SELECT child FROM AppBundle\Entity\Child child ORDER BY child.name';
//        $query = $this->getEntityManager()->createQuery($dql);
//       return $query->execute();

        $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'DESC');
        $query= $qb->getQuery();
        return $query->execute();
    }
    public function findChildrenByParent($parentId)
    {
        return $this->createQueryBuilder('child')
//            ->addOrderBy('child.name', 'DESC')
            ->leftJoin('child.parent', 'parent')
            ->andWhere('parent.id = :id')
            ->setParameter('id', $parentId)
            ->getQuery()
            ->execute();


    }
}

